\c dv01;

CREATE TABLE IF NOT EXISTS loans
(
    id                                         BIGINT PRIMARY KEY,
    member_id                                  BIGINT,
    loan_amnt                                  NUMERIC,
    funded_amnt                                NUMERIC,
    funded_amnt_inv                            NUMERIC,
    term                                       VARCHAR(15),
    int_rate                                   VARCHAR(10),
    installment                                NUMERIC,
    grade                                      VARCHAR(2),
    sub_grade                                  VARCHAR(3),
    emp_title                                  VARCHAR(100),
    emp_length                                 VARCHAR(15),
    home_ownership                             VARCHAR(15),
    annual_inc                                 NUMERIC,
    verification_status                        VARCHAR(20),
    issue_d                                    VARCHAR(10),
    loan_status                                VARCHAR(20),
    pymnt_plan                                 VARCHAR(1),
    url                                        VARCHAR(255),
    "desc"                                     TEXT,
    purpose                                    VARCHAR(50),
    title                                      VARCHAR(100),
    zip_code                                   VARCHAR(10),
    addr_state                                 VARCHAR(2),
    dti                                        NUMERIC,
    delinq_2yrs                                INTEGER,
    earliest_cr_line                           VARCHAR(10),
    fico_range_low                             INTEGER,
    fico_range_high                            INTEGER,
    inq_last_6mths                             INTEGER,
    mths_since_last_delinq                     INTEGER,
    mths_since_last_record                     INTEGER,
    open_acc                                   INTEGER,
    pub_rec                                    INTEGER,
    revol_bal                                  NUMERIC,
    revol_util                                 VARCHAR(10),
    total_acc                                  INTEGER,
    initial_list_status                        VARCHAR(1),
    out_prncp                                  NUMERIC,
    out_prncp_inv                              NUMERIC,
    total_pymnt                                NUMERIC,
    total_pymnt_inv                            NUMERIC,
    total_rec_prncp                            NUMERIC,
    total_rec_int                              NUMERIC,
    total_rec_late_fee                         NUMERIC,
    recoveries                                 NUMERIC,
    collection_recovery_fee                    NUMERIC,
    last_pymnt_d                               VARCHAR(10),
    last_pymnt_amnt                            NUMERIC,
    next_pymnt_d                               VARCHAR(10),
    last_credit_pull_d                         VARCHAR(10),
    last_fico_range_high                       INTEGER,
    last_fico_range_low                        INTEGER,
    collections_12_mths_ex_med                 INTEGER,
    mths_since_last_major_derog                INTEGER,
    policy_code                                INTEGER,
    application_type                           VARCHAR(20),
    annual_inc_joint                           NUMERIC,
    dti_joint                                  NUMERIC,
    verification_status_joint                  VARCHAR(20),
    acc_now_delinq                             INTEGER,
    tot_coll_amt                               NUMERIC,
    tot_cur_bal                                NUMERIC,
    open_acc_6m                                INTEGER,
    open_act_il                                INTEGER,
    open_il_12m                                INTEGER,
    open_il_24m                                INTEGER,
    mths_since_rcnt_il                         INTEGER,
    total_bal_il                               NUMERIC,
    il_util                                    NUMERIC,
    open_rv_12m                                INTEGER,
    open_rv_24m                                INTEGER,
    max_bal_bc                                 NUMERIC,
    all_util                                   NUMERIC,
    total_rev_hi_lim                           NUMERIC,
    inq_fi                                     INTEGER,
    total_cu_tl                                INTEGER,
    inq_last_12m                               INTEGER,
    acc_open_past_24mths                       INTEGER,
    avg_cur_bal                                NUMERIC,
    bc_open_to_buy                             NUMERIC,
    bc_util                                    NUMERIC,
    chargeoff_within_12_mths                   INTEGER,
    delinq_amnt                                NUMERIC,
    mo_sin_old_il_acct                         INTEGER,
    mo_sin_old_rev_tl_op                       INTEGER,
    mo_sin_rcnt_rev_tl_op                      INTEGER,
    mo_sin_rcnt_tl                             INTEGER,
    mort_acc                                   INTEGER,
    mths_since_recent_bc                       INTEGER,
    mths_since_recent_bc_dlq                   INTEGER,
    mths_since_recent_inq                      INTEGER,
    mths_since_recent_revol_delinq             INTEGER,
    num_accts_ever_120_pd                      INTEGER,
    num_actv_bc_tl                             INTEGER,
    num_actv_rev_tl                            INTEGER,
    num_bc_sats                                INTEGER,
    num_bc_tl                                  INTEGER,
    num_il_tl                                  INTEGER,
    num_op_rev_tl                              INTEGER,
    num_rev_accts                              INTEGER,
    num_rev_tl_bal_gt_0                        INTEGER,
    num_sats                                   INTEGER,
    num_tl_120dpd_2m                           INTEGER,
    num_tl_30dpd                               INTEGER,
    num_tl_90g_dpd_24m                         INTEGER,
    num_tl_op_past_12m                         INTEGER,
    pct_tl_nvr_dlq                             NUMERIC,
    percent_bc_gt_75                           NUMERIC,
    pub_rec_bankruptcies                       INTEGER,
    tax_liens                                  INTEGER,
    tot_hi_cred_lim                            NUMERIC,
    total_bal_ex_mort                          NUMERIC,
    total_bc_limit                             NUMERIC,
    total_il_high_credit_limit                 NUMERIC,
    revol_bal_joint                            NUMERIC,
    sec_app_fico_range_low                     INTEGER,
    sec_app_fico_range_high                    INTEGER,
    sec_app_earliest_cr_line                   VARCHAR(10),
    sec_app_inq_last_6mths                     INTEGER,
    sec_app_mort_acc                           INTEGER,
    sec_app_open_acc                           INTEGER,
    sec_app_revol_util                         NUMERIC,
    sec_app_open_act_il                        INTEGER,
    sec_app_num_rev_accts                      INTEGER,
    sec_app_chargeoff_within_12_mths           INTEGER,
    sec_app_collections_12_mths_ex_med         INTEGER,
    sec_app_mths_since_last_major_derog        INTEGER,
    hardship_flag                              VARCHAR(1),
    hardship_type                              VARCHAR(50),
    hardship_reason                            VARCHAR(100),
    hardship_status                            VARCHAR(20),
    deferral_term                              INTEGER,
    hardship_amount                            NUMERIC,
    hardship_start_date                        VARCHAR(10),
    hardship_end_date                          VARCHAR(10),
    payment_plan_start_date                    VARCHAR(10),
    hardship_length                            INTEGER,
    hardship_dpd                               INTEGER,
    hardship_loan_status                       VARCHAR(20),
    orig_projected_additional_accrued_interest NUMERIC,
    hardship_payoff_balance_amount             NUMERIC,
    hardship_last_payment_amount               NUMERIC,
    debt_settlement_flag                       VARCHAR(1),
    debt_settlement_flag_date                  VARCHAR(10),
    settlement_status                          VARCHAR(20),
    settlement_date                            VARCHAR(10),
    settlement_amount                          NUMERIC,
    settlement_percentage                      NUMERIC,
    settlement_term                            INTEGER
);

COPY loans FROM '/data/loan_data.csv'
    WITH (
    DELIMITER ',',
    QUOTE '"',
    FORMAT 'csv',
    FORCE_NULL (member_id, mths_since_last_delinq, avg_cur_bal, mths_since_last_record,mths_since_last_major_derog, annual_inc_joint, dti_joint, bc_open_to_buy, bc_util, mths_since_recent_bc_dlq, mths_since_recent_bc, mths_since_recent_inq, mths_since_recent_revol_delinq, percent_bc_gt_75, il_util, mths_since_rcnt_il, mo_sin_old_il_acct, all_util, dti, revol_bal_joint, num_tl_120dpd_2m, sec_app_fico_range_low, sec_app_fico_range_high, sec_app_inq_last_6mths, sec_app_mort_acc, sec_app_open_acc, sec_app_revol_util, sec_app_open_act_il, sec_app_num_rev_accts, sec_app_chargeoff_within_12_mths, sec_app_collections_12_mths_ex_med, sec_app_mths_since_last_major_derog, deferral_term, hardship_amount, hardship_length, hardship_dpd, orig_projected_additional_accrued_interest, hardship_payoff_balance_amount, hardship_last_payment_amount, settlement_amount, settlement_percentage, settlement_term),
    HEADER
    );

CREATE TABLE IF NOT EXISTS loan_data
(
    id              BIGINT PRIMARY KEY,
    loan_amount     INTEGER,
    funded_amount   INTEGER,
    term            VARCHAR(255),
    interest_rate   VARCHAR(10),
    grade           VARCHAR(2),
    sub_grade       VARCHAR(3),
    employee_title  VARCHAR(255),
    home_ownership  VARCHAR(255),
    issued_date     VARCHAR(10),
    loan_status     VARCHAR(255),
    zip_code        VARCHAR(10),
    state_address   VARCHAR(2),
    fico_range_low  INTEGER,
    fico_range_high INTEGER
);

TRUNCATE TABLE loan_data;

INSERT INTO loan_data
SELECT id,
       loan_amnt,
       funded_amnt,
       TRIM(term),
       TRIM(int_rate),
       TRIM(grade),
       TRIM(sub_grade),
       TRIM(emp_title),
       TRIM(home_ownership),
       TRIM(issue_d),
       TRIM(loan_status),
       TRIM(zip_code),
       TRIM(addr_state),
       fico_range_low,
       fico_range_high
FROM loans;
